### ISSUE TITLE
paypal button does not work

### ISSUE THREAD

**Issue by PawelSpoon** [jobe-m/ownkeepass#14]
the paypal button mentioned in openreoos does not work

**Comment by jobe-m** [comment]
I checked that with clicking the button on openrepos the paypal side opens correctly.
What is the actual error you experienced? Did you try to send some money and that was now working?

**Comment by PawelSpoon** [comment]
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=5KR2WTZ8FMRQQ


it shows a paypal page with an errormessage. here the link

**Comment by jobe-m** [comment]
For me the link on openrepos is working. Can you check why your link above has a `&amp;` instead of only a `&` character. Below is the link on [openrepos](https://openrepos.net/content/jobe/ownkeepass) when I copy-paste it:
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=5KR2WTZ8FMRQQ
