### ISSUE TITLE
build error cause of keepass2_database

### ISSUE THREAD

**Issue by ghost** [jobe-m/ownkeepass#15]
i tried a few versions of keepass (the referenced, 2.0.2 release and latest), but i get always same errors caused by Database.h/cpp 

i assume it's a known issue, but if you need it, i can give you a log file.

thanks for this great software

**Comment by ghost** [comment]
i fixed the issue, it was just #include <QObject> missing in Database.h

**Comment by jobe-m** [comment]
You are right. Sorry, I forgot to mention it on the readme page. I will do it now.
Maybe I can try to upstream this change to the keepassx project so that it is not needed.
Then only a checkout of the git submodule will be enough.

The change is:
Add `#include <QObject>` to the Keepass 2 database header file `ownkeepass/common/src/keepassPlugin/keepass2_database/keepassx/src/core/Database.h`.

**Comment by jobe-m** [comment]
Maybe a bit later adding to the readme... not now...
